2025-04-19 11:55:59,160 - INFO - Traceback (most recent call last):
  File "/root/catkin_ws/src/tactracer_robot/bumblebee/scripts/node_SSESVR_log.py", line 753, in service_jog
    listReturnTmp.append(dicMotorH)
UnboundLocalError: local variable 'dicMotorH' referenced before assignment
:dispatch_request:service_jog:logSSE_error
2025-04-19 11:57:46,277 - INFO - Traceback (most recent call last):
  File "/root/catkin_ws/src/tactracer_robot/bumblebee/scripts/node_SSESVR_log.py", line 753, in service_jog
    if endnode in GetSpeicificEPCNodeInfo():
TypeError: argument of type 'NoneType' is not iterable
:dispatch_request:service_jog:logSSE_error
2025-04-19 11:58:45,464 - INFO - Traceback (most recent call last):
  File "/root/catkin_ws/src/tactracer_robot/bumblebee/scripts/node_SSESVR_log.py", line 754, in service_jog
    if endnode in lsSpecialNodes:
TypeError: argument of type 'NoneType' is not iterable
:dispatch_request:service_jog:logSSE_error
2025-04-19 12:03:33,006 - INFO - Traceback (most recent call last):
  File "/root/catkin_ws/src/tactracer_robot/bumblebee/scripts/node_SSESVR_log.py", line 753, in service_jog
    lsSpecialNodes = GetSpeicificEPCNodeInfo()
  File "/root/catkin_ws/src/tactracer_robot/bumblebee/scripts/node_SSESVR_log.py", line 88, in GetSpeicificEPCNodeInfo
    state_keys: list[str] = list(GetCrossInfo.keys())
AttributeError: 'function' object has no attribute 'keys'
:dispatch_request:service_jog:logSSE_error
2025-04-19 12:03:46,500 - INFO - Traceback (most recent call last):
  File "/root/catkin_ws/src/tactracer_robot/bumblebee/scripts/node_SSESVR_log.py", line 753, in service_jog
    lsSpecialNodes = GetSpeicificEPCNodeInfo()
  File "/root/catkin_ws/src/tactracer_robot/bumblebee/scripts/node_SSESVR_log.py", line 88, in GetSpeicificEPCNodeInfo
    state_keys: list[str] = list(GetCrossInfo.keys())
AttributeError: 'function' object has no attribute 'keys'
:dispatch_request:service_jog:logSSE_error
2025-04-19 12:04:03,940 - INFO - Traceback (most recent call last):
  File "/root/catkin_ws/src/tactracer_robot/bumblebee/scripts/node_SSESVR_log.py", line 753, in service_jog
    lsSpecialNodes = GetSpeicificEPCNodeInfo()
  File "/root/catkin_ws/src/tactracer_robot/bumblebee/scripts/node_SSESVR_log.py", line 88, in GetSpeicificEPCNodeInfo
    state_keys: list[str] = list(GetCrossInfo.keys())
AttributeError: 'function' object has no attribute 'keys'
:dispatch_request:service_jog:logSSE_error
2025-04-22 09:38:58,567 - INFO - Traceback (most recent call last):
  File "/root/catkin_ws/src/tactracer_robot/bumblebee/scripts/node_SSESVR_log.py", line 483, in callback
    if MonitoringField.ALM_NM.name in recvDataMap:
TypeError: argument of type 'int' is not iterable
:_invoke_callback:callback:logSSE_error
2025-04-22 09:40:02,174 - INFO - Traceback (most recent call last):
  File "/root/catkin_ws/src/tactracer_robot/bumblebee/scripts/node_SSESVR_log.py", line 483, in callback
    if MonitoringField.ALM_NM.name in recvDataMap:
TypeError: argument of type 'int' is not iterable
:_invoke_callback:callback:logSSE_error
2025-04-22 09:40:10,972 - INFO - Traceback (most recent call last):
  File "/root/catkin_ws/src/tactracer_robot/bumblebee/scripts/node_SSESVR_log.py", line 483, in callback
    if MonitoringField.ALM_NM.name in recvDataMap:
TypeError: argument of type 'int' is not iterable
:_invoke_callback:callback:logSSE_error
2025-04-22 10:31:14,448 - INFO - Traceback (most recent call last):
  File "/root/catkin_ws/src/tactracer_robot/bumblebee/scripts/node_SSESVR_log.py", line 483, in callback
    if MonitoringField.ALM_NM.name in recvDataMap:
TypeError: argument of type 'int' is not iterable
:_invoke_callback:callback:logSSE_error
2025-04-22 10:31:35,218 - INFO - Traceback (most recent call last):
  File "/root/catkin_ws/src/tactracer_robot/bumblebee/scripts/node_SSESVR_log.py", line 483, in callback
    if MonitoringField.ALM_NM.name in recvDataMap:
TypeError: argument of type 'int' is not iterable
:_invoke_callback:callback:logSSE_error
2025-04-22 10:32:20,972 - INFO - Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_String.py", line 54, in serialize
    length = len(_x)
TypeError: object of type 'int' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_String.py", line 60, in serialize
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 393, in _check_types
    check_type(n, t, getattr(self, n))
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 285, in check_type
    raise SerializationError('field %s must be of type bytes or an ascii string' % field_name)
genpy.message.SerializationError: field data must be of type bytes or an ascii string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/catkin_ws/src/tactracer_robot/bumblebee/scripts/node_SSESVR_log.py", line 894, in service_cmd
    pub_BLB_CMD.publish(qNumber)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 886, in publish
    raise ROSSerializationException(str(e))
rospy.exceptions.ROSSerializationException: field data must be of type bytes or an ascii string
:dispatch_request:service_cmd:logSSE_error
